#pragma once
#include <ninja.h>

const NJS_MATERIAL matlist_02FD0F64[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FD116C[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FD24CC[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FD4810[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FD4AC0[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FD4D58[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FD583C[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FD59B8[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FD5B4C[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FD5CE4[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FD5E7C[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FD6018[] = {
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 26, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_FLIP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFF00FFB2 }, { 0x00FFFFFF }, 11, 27, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 25, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 22, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 24, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 22, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFB2FF00 }, { 0x00FFFFFF }, 11, 28, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 22, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 22, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 26, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 25, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 23, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_FLIP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FD75F8[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FD9148[] = {
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 2, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 2, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 14, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 16, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 17, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 15, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0x7F000000 }, { 0x00FFFFFF }, 11, 32, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FDC7B8[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 35, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 35, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 36, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FDE5AC[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 34, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FE0104[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 7, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 7, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FE4F68[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 34, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FE6E6C[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 5, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 8, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FE7A18[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 5, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 8, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FE8538[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 5, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 8, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FE90A0[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 5, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 8, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FE9C48[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 5, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FE9F58[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 5, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 8, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FEAA38[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 5, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 8, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FEB5E0[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 5, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 8, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FEB850[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 5, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 8, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FEC420[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 5, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 8, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FECFC8[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 5, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_DOUBLE_SIDE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 5, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FED238[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 5, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 8, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FEDB10[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 5, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 8, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FEE5E0[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 5, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 8, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FEEF78[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 5, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 8, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FEFA58[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 32, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FEFBDC[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 32, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FEFE7C[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 32, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF002C[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 32, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF01B4[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 32, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF03C4[] = {
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 10, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_FLIP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0x7F000000 }, { 0x00FFFFFF }, 11, 32, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF0BC8[] = {
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 1, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 1, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 11, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 1, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 2, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF1EB8[] = {
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 29, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 0, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 19, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 2, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 20, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 33, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF33D0[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 32, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF3500[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF38D0[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF3CA0[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF4070[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF4440[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF4810[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF4BE0[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF4FB0[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF5380[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF5750[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF5B20[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF5EF0[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF62C0[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF6690[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF6A60[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF6E30[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF7200[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF75D0[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF79A0[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF7D70[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 12, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF7EF8[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 37, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_FLIP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FF9BD4[] = {
	{ { 0x37FFFFFF }, { 0x00FFFFFF }, 11, 32, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0x37FFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FFA2D0[] = {
	{ { 0x37FFFFFF }, { 0x00FFFFFF }, 11, 32, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0x37FFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FFA9D0[] = {
	{ { 0x37FFFFFF }, { 0x00FFFFFF }, 11, 32, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0x37FFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FFB0D0[] = {
	{ { 0x37FFFFFF }, { 0x00FFFFFF }, 11, 32, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0x37FFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FFB7D0[] = {
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 2, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 39, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 2, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 30, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 21, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FFC674[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 36, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 35, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 35, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FFD018[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 36, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 35, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 36, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FFE3E4[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 13, (Uint32)0x40 | NJD_DA_ONE | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_DOUBLE_SIDE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 13, (Uint32)0x40 | NJD_DA_ONE | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_030007B4[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 42, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03000C10[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_DOUBLE_SIDE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03001964[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 42, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03001DC0[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03002B14[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 42, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03002F70[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03003CC4[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 42, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03004120[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FD83B0[] = {
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 4, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 38, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 18, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 40, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_02FD8938[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 1, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 41, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 4, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 3, (Uint32)0x40 | NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};
