#pragma once
#include <ninja.h>

const NJS_MATERIAL matlist_03236884[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03236AF8[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03236D08[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03236E70[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03237250[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03237560[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03237A50[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03237FB8[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03238388[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03238E54[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_032390C0[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03239438[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03239AD4[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03239C40[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03239FE0[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0323A148[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0323A2B0[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0323A444[] = {
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0323A9D8[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0323AC10[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0323B7B8[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0323B8F0[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0323BA98[] = {
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0323BCD0[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0323BE38[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0323BFA0[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 7, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 38, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 2, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0323C4F0[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 14, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 14, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 14, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 14, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 14, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 14, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 14, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 13, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 14, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 24, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 14, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 17, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 15, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 16, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03243EB0[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 3, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 2, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 38, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 7, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 3, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 2, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_032446F0[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 25, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 26, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 25, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 36, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 26, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03245900[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 4, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 24, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 36, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 23, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 24, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 5, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03248830[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 25, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 35, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 24, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03249754[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 27, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 7, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 7, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0324B524[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 18, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 31, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0324C238[] = {
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 15, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_DOUBLE_SIDE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 17, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 15, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 16, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0324C9EC[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 19, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0324CB08[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 19, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0324CC28[] = {
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 1, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 27, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 39, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 32, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 1, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 20, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0324E098[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 2, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 2, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 20, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 3, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 2, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 3, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 2, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 3, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 32, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 20, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 39, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 1, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 2, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03254028[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 4, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03255714[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 34, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_FLIP_U | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03257214[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 34, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03257E00[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 34, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_FLIP_U | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03258DA0[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 34, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_032594B0[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 34, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_FLIP_U | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0325A450[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 34, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0325AB60[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 34, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_FLIP_U | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0325B744[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 34, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0325BCB8[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 34, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_DOUBLE_SIDE | NJD_FLAG_FLIP_U | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0325D7A4[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 34, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0325E390[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 23, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 5, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 24, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 4, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 36, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_FLIP_U | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 24, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0325F660[] = {
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 9, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 4, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 9, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 9, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03260160[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 8, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 27, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 27, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 8, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03261900[] = {
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 2, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 2, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 3, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 38, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 7, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03262058[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 22, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 37, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03262DDC[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 22, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 37, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 22, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03264B08[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 12, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03264D60[] = {
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 38, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 29, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 30, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 29, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 29, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 29, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 29, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 6, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 29, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 28, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 38, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_U | NJD_FLAG_FLIP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 29, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 29, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 30, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_03269D68[] = {
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 10, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 21, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 21, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 21, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFB2B2B2 }, { 0x00FFFFFF }, 11, 21, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 33, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
	{ { 0xFFFFFFFF }, { 0x00FFFFFF }, 11, 11, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_U | NJD_FLAG_CLAMP_V | NJD_FLAG_USE_TEXTURE | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0326A754[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};

const NJS_MATERIAL matlist_0326A8E4[] = {
	{ { 0xFFFFFFFF }, { 0x00000000 }, 0, 0, (Uint32)NJD_DA_INV_SRC | NJD_D_100 | NJD_FILTER_BILINEAR | NJD_SA_SRC },
};
